// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: occupations/BlueBike.proto

package occupations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeoPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lon float64 `protobuf:"fixed64,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat float64 `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
}

func (x *GeoPoint) Reset() {
	*x = GeoPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_occupations_BlueBike_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoPoint) ProtoMessage() {}

func (x *GeoPoint) ProtoReflect() protoreflect.Message {
	mi := &file_occupations_BlueBike_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoPoint.ProtoReflect.Descriptor instead.
func (*GeoPoint) Descriptor() ([]byte, []int) {
	return file_occupations_BlueBike_proto_rawDescGZIP(), []int{0}
}

func (x *GeoPoint) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GeoPoint) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

type BlueBikeOccupation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastSeen       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_seen,proto3" json:"last_seen,omitempty"`
	Id             int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	BikesInUse     int32                  `protobuf:"varint,4,opt,name=bikes_in_use,json=bikesInUse,proto3" json:"bikes_in_use,omitempty"`
	BikesAvailable int32                  `protobuf:"varint,5,opt,name=bikes_available,json=bikesAvailable,proto3" json:"bikes_available,omitempty"`
	Geopoint       *GeoPoint              `protobuf:"bytes,8,opt,name=geopoint,proto3" json:"geopoint,omitempty"`
	Type           string                 `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *BlueBikeOccupation) Reset() {
	*x = BlueBikeOccupation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_occupations_BlueBike_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlueBikeOccupation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlueBikeOccupation) ProtoMessage() {}

func (x *BlueBikeOccupation) ProtoReflect() protoreflect.Message {
	mi := &file_occupations_BlueBike_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlueBikeOccupation.ProtoReflect.Descriptor instead.
func (*BlueBikeOccupation) Descriptor() ([]byte, []int) {
	return file_occupations_BlueBike_proto_rawDescGZIP(), []int{1}
}

func (x *BlueBikeOccupation) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *BlueBikeOccupation) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BlueBikeOccupation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BlueBikeOccupation) GetBikesInUse() int32 {
	if x != nil {
		return x.BikesInUse
	}
	return 0
}

func (x *BlueBikeOccupation) GetBikesAvailable() int32 {
	if x != nil {
		return x.BikesAvailable
	}
	return 0
}

func (x *BlueBikeOccupation) GetGeopoint() *GeoPoint {
	if x != nil {
		return x.Geopoint
	}
	return nil
}

func (x *BlueBikeOccupation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_occupations_BlueBike_proto protoreflect.FileDescriptor

var file_occupations_BlueBike_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x42, 0x6c,
	0x75, 0x65, 0x42, 0x69, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a,
	0x08, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x22, 0xf8, 0x01,
	0x0a, 0x12, 0x42, 0x6c, 0x75, 0x65, 0x42, 0x69, 0x6b, 0x65, 0x4f, 0x63, 0x63, 0x75, 0x70, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x65, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x5f, 0x75,
	0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x49,
	0x6e, 0x55, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x5f, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x62,
	0x69, 0x6b, 0x65, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x25, 0x0a,
	0x08, 0x67, 0x65, 0x6f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x67, 0x65, 0x6f, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x35, 0x42, 0x0d, 0x42, 0x6c, 0x75, 0x65,
	0x42, 0x69, 0x6b, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x22, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x32, 0x30, 0x32, 0x34, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x67, 0x65, 0x6e, 0x2f, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_occupations_BlueBike_proto_rawDescOnce sync.Once
	file_occupations_BlueBike_proto_rawDescData = file_occupations_BlueBike_proto_rawDesc
)

func file_occupations_BlueBike_proto_rawDescGZIP() []byte {
	file_occupations_BlueBike_proto_rawDescOnce.Do(func() {
		file_occupations_BlueBike_proto_rawDescData = protoimpl.X.CompressGZIP(file_occupations_BlueBike_proto_rawDescData)
	})
	return file_occupations_BlueBike_proto_rawDescData
}

var file_occupations_BlueBike_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_occupations_BlueBike_proto_goTypes = []interface{}{
	(*GeoPoint)(nil),              // 0: GeoPoint
	(*BlueBikeOccupation)(nil),    // 1: BlueBikeOccupation
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_occupations_BlueBike_proto_depIdxs = []int32{
	2, // 0: BlueBikeOccupation.last_seen:type_name -> google.protobuf.Timestamp
	0, // 1: BlueBikeOccupation.geopoint:type_name -> GeoPoint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_occupations_BlueBike_proto_init() }
func file_occupations_BlueBike_proto_init() {
	if File_occupations_BlueBike_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_occupations_BlueBike_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeoPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_occupations_BlueBike_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlueBikeOccupation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_occupations_BlueBike_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_occupations_BlueBike_proto_goTypes,
		DependencyIndexes: file_occupations_BlueBike_proto_depIdxs,
		MessageInfos:      file_occupations_BlueBike_proto_msgTypes,
	}.Build()
	File_occupations_BlueBike_proto = out.File
	file_occupations_BlueBike_proto_rawDesc = nil
	file_occupations_BlueBike_proto_goTypes = nil
	file_occupations_BlueBike_proto_depIdxs = nil
}
