// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: occupations/stallinggent.proto

package occupations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	common "stage2024/pkg/protogen/common"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StallingGent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time           string           `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Facilityname   string           `protobuf:"bytes,2,opt,name=facilityname,proto3" json:"facilityname,omitempty"`
	Id             string           `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Totalplaces    int32            `protobuf:"varint,4,opt,name=totalplaces,proto3" json:"totalplaces,omitempty"`
	Freeplaces     int32            `protobuf:"varint,5,opt,name=freeplaces,proto3" json:"freeplaces,omitempty"`
	Occupiedplaces int32            `protobuf:"varint,6,opt,name=occupiedplaces,proto3" json:"occupiedplaces,omitempty"`
	Bezetting      int32            `protobuf:"varint,7,opt,name=bezetting,proto3" json:"bezetting,omitempty"`
	Location       *common.Location `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *StallingGent) Reset() {
	*x = StallingGent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_occupations_stallinggent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StallingGent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StallingGent) ProtoMessage() {}

func (x *StallingGent) ProtoReflect() protoreflect.Message {
	mi := &file_occupations_stallinggent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StallingGent.ProtoReflect.Descriptor instead.
func (*StallingGent) Descriptor() ([]byte, []int) {
	return file_occupations_stallinggent_proto_rawDescGZIP(), []int{0}
}

func (x *StallingGent) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *StallingGent) GetFacilityname() string {
	if x != nil {
		return x.Facilityname
	}
	return ""
}

func (x *StallingGent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StallingGent) GetTotalplaces() int32 {
	if x != nil {
		return x.Totalplaces
	}
	return 0
}

func (x *StallingGent) GetFreeplaces() int32 {
	if x != nil {
		return x.Freeplaces
	}
	return 0
}

func (x *StallingGent) GetOccupiedplaces() int32 {
	if x != nil {
		return x.Occupiedplaces
	}
	return 0
}

func (x *StallingGent) GetBezetting() int32 {
	if x != nil {
		return x.Bezetting
	}
	return 0
}

func (x *StallingGent) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

var File_occupations_stallinggent_proto protoreflect.FileDescriptor

var file_occupations_stallinggent_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x02, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x6c,
	0x6c, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x66, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x66, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x72, 0x65, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x72, 0x65, 0x65, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6f, 0x63, 0x63, 0x75,
	0x70, 0x69, 0x65, 0x64, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x65,
	0x7a, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62,
	0x65, 0x7a, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x2c, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x39, 0x42, 0x11, 0x53, 0x74, 0x61, 0x6c, 0x6c, 0x69,
	0x6e, 0x67, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x22, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x32, 0x30, 0x32, 0x34, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_occupations_stallinggent_proto_rawDescOnce sync.Once
	file_occupations_stallinggent_proto_rawDescData = file_occupations_stallinggent_proto_rawDesc
)

func file_occupations_stallinggent_proto_rawDescGZIP() []byte {
	file_occupations_stallinggent_proto_rawDescOnce.Do(func() {
		file_occupations_stallinggent_proto_rawDescData = protoimpl.X.CompressGZIP(file_occupations_stallinggent_proto_rawDescData)
	})
	return file_occupations_stallinggent_proto_rawDescData
}

var file_occupations_stallinggent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_occupations_stallinggent_proto_goTypes = []interface{}{
	(*StallingGent)(nil),    // 0: StallingGent
	(*common.Location)(nil), // 1: common.Location
}
var file_occupations_stallinggent_proto_depIdxs = []int32{
	1, // 0: StallingGent.location:type_name -> common.Location
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_occupations_stallinggent_proto_init() }
func file_occupations_stallinggent_proto_init() {
	if File_occupations_stallinggent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_occupations_stallinggent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StallingGent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_occupations_stallinggent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_occupations_stallinggent_proto_goTypes,
		DependencyIndexes: file_occupations_stallinggent_proto_depIdxs,
		MessageInfos:      file_occupations_stallinggent_proto_msgTypes,
	}.Build()
	File_occupations_stallinggent_proto = out.File
	file_occupations_stallinggent_proto_rawDesc = nil
	file_occupations_stallinggent_proto_goTypes = nil
	file_occupations_stallinggent_proto_depIdxs = nil
}
