// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_abandoned.proto

// Protobuf Java Version: 4.26.1
package proto;

/**
 * Protobuf type {@code bike_abandoned}
 */
public final class bike_abandoned extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bike_abandoned)
    bike_abandonedOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      bike_abandoned.class.getName());
  }
  // Use bike_abandoned.newBuilder() to construct.
  private bike_abandoned(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private bike_abandoned() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.BikeAbandonedProto.internal_static_bike_abandoned_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.BikeAbandonedProto.internal_static_bike_abandoned_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.bike_abandoned.class, proto.bike_abandoned.Builder.class);
  }

  private int bitField0_;
  public static final int TIME_STAMP_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp timeStamp_;
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return Whether the timeStamp field is set.
   */
  @java.lang.Override
  public boolean hasTimeStamp() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return The timeStamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimeStamp() {
    return timeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder() {
    return timeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
  }

  public static final int BIKE_FIELD_NUMBER = 2;
  private proto.abandoned_bike bike_;
  /**
   * <code>.abandoned_bike bike = 2 [json_name = "bike"];</code>
   * @return Whether the bike field is set.
   */
  @java.lang.Override
  public boolean hasBike() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.abandoned_bike bike = 2 [json_name = "bike"];</code>
   * @return The bike.
   */
  @java.lang.Override
  public proto.abandoned_bike getBike() {
    return bike_ == null ? proto.abandoned_bike.getDefaultInstance() : bike_;
  }
  /**
   * <code>.abandoned_bike bike = 2 [json_name = "bike"];</code>
   */
  @java.lang.Override
  public proto.abandoned_bikeOrBuilder getBikeOrBuilder() {
    return bike_ == null ? proto.abandoned_bike.getDefaultInstance() : bike_;
  }

  public static final int USER_FIELD_NUMBER = 3;
  private user_identification user_;
  /**
   * <code>.user_identification user = 3 [json_name = "user"];</code>
   * @return Whether the user field is set.
   */
  @java.lang.Override
  public boolean hasUser() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.user_identification user = 3 [json_name = "user"];</code>
   * @return The user.
   */
  @java.lang.Override
  public user_identification getUser() {
    return user_ == null ? user_identification.getDefaultInstance() : user_;
  }
  /**
   * <code>.user_identification user = 3 [json_name = "user"];</code>
   */
  @java.lang.Override
  public user_identificationOrBuilder getUserOrBuilder() {
    return user_ == null ? user_identification.getDefaultInstance() : user_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getTimeStamp());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getBike());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getUser());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTimeStamp());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBike());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUser());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.bike_abandoned)) {
      return super.equals(obj);
    }
    proto.bike_abandoned other = (proto.bike_abandoned) obj;

    if (hasTimeStamp() != other.hasTimeStamp()) return false;
    if (hasTimeStamp()) {
      if (!getTimeStamp()
          .equals(other.getTimeStamp())) return false;
    }
    if (hasBike() != other.hasBike()) return false;
    if (hasBike()) {
      if (!getBike()
          .equals(other.getBike())) return false;
    }
    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTimeStamp()) {
      hash = (37 * hash) + TIME_STAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
    }
    if (hasBike()) {
      hash = (37 * hash) + BIKE_FIELD_NUMBER;
      hash = (53 * hash) + getBike().hashCode();
    }
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.bike_abandoned parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.bike_abandoned parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.bike_abandoned parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.bike_abandoned parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.bike_abandoned parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.bike_abandoned parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.bike_abandoned parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.bike_abandoned parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static proto.bike_abandoned parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static proto.bike_abandoned parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.bike_abandoned parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.bike_abandoned parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.bike_abandoned prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bike_abandoned}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bike_abandoned)
      proto.bike_abandonedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.BikeAbandonedProto.internal_static_bike_abandoned_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.BikeAbandonedProto.internal_static_bike_abandoned_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.bike_abandoned.class, proto.bike_abandoned.Builder.class);
    }

    // Construct using proto.bike_abandoned.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getTimeStampFieldBuilder();
        getBikeFieldBuilder();
        getUserFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      bike_ = null;
      if (bikeBuilder_ != null) {
        bikeBuilder_.dispose();
        bikeBuilder_ = null;
      }
      user_ = null;
      if (userBuilder_ != null) {
        userBuilder_.dispose();
        userBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.BikeAbandonedProto.internal_static_bike_abandoned_descriptor;
    }

    @java.lang.Override
    public proto.bike_abandoned getDefaultInstanceForType() {
      return proto.bike_abandoned.getDefaultInstance();
    }

    @java.lang.Override
    public proto.bike_abandoned build() {
      proto.bike_abandoned result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.bike_abandoned buildPartial() {
      proto.bike_abandoned result = new proto.bike_abandoned(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(proto.bike_abandoned result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.timeStamp_ = timeStampBuilder_ == null
            ? timeStamp_
            : timeStampBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.bike_ = bikeBuilder_ == null
            ? bike_
            : bikeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.user_ = userBuilder_ == null
            ? user_
            : userBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.bike_abandoned) {
        return mergeFrom((proto.bike_abandoned)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.bike_abandoned other) {
      if (other == proto.bike_abandoned.getDefaultInstance()) return this;
      if (other.hasTimeStamp()) {
        mergeTimeStamp(other.getTimeStamp());
      }
      if (other.hasBike()) {
        mergeBike(other.getBike());
      }
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTimeStampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getBikeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getUserFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Timestamp timeStamp_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeStampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     * @return Whether the timeStamp field is set.
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     * @return The timeStamp.
     */
    public com.google.protobuf.Timestamp getTimeStamp() {
      if (timeStampBuilder_ == null) {
        return timeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
      } else {
        return timeStampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public Builder setTimeStamp(com.google.protobuf.Timestamp value) {
      if (timeStampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeStamp_ = value;
      } else {
        timeStampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public Builder setTimeStamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timeStampBuilder_ == null) {
        timeStamp_ = builderForValue.build();
      } else {
        timeStampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public Builder mergeTimeStamp(com.google.protobuf.Timestamp value) {
      if (timeStampBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          timeStamp_ != null &&
          timeStamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimeStampBuilder().mergeFrom(value);
        } else {
          timeStamp_ = value;
        }
      } else {
        timeStampBuilder_.mergeFrom(value);
      }
      if (timeStamp_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public Builder clearTimeStamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimeStampBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTimeStampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder() {
      if (timeStampBuilder_ != null) {
        return timeStampBuilder_.getMessageOrBuilder();
      } else {
        return timeStamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimeStampFieldBuilder() {
      if (timeStampBuilder_ == null) {
        timeStampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimeStamp(),
                getParentForChildren(),
                isClean());
        timeStamp_ = null;
      }
      return timeStampBuilder_;
    }

    private proto.abandoned_bike bike_;
    private com.google.protobuf.SingleFieldBuilder<
        proto.abandoned_bike, proto.abandoned_bike.Builder, proto.abandoned_bikeOrBuilder> bikeBuilder_;
    /**
     * <code>.abandoned_bike bike = 2 [json_name = "bike"];</code>
     * @return Whether the bike field is set.
     */
    public boolean hasBike() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.abandoned_bike bike = 2 [json_name = "bike"];</code>
     * @return The bike.
     */
    public proto.abandoned_bike getBike() {
      if (bikeBuilder_ == null) {
        return bike_ == null ? proto.abandoned_bike.getDefaultInstance() : bike_;
      } else {
        return bikeBuilder_.getMessage();
      }
    }
    /**
     * <code>.abandoned_bike bike = 2 [json_name = "bike"];</code>
     */
    public Builder setBike(proto.abandoned_bike value) {
      if (bikeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bike_ = value;
      } else {
        bikeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.abandoned_bike bike = 2 [json_name = "bike"];</code>
     */
    public Builder setBike(
        proto.abandoned_bike.Builder builderForValue) {
      if (bikeBuilder_ == null) {
        bike_ = builderForValue.build();
      } else {
        bikeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.abandoned_bike bike = 2 [json_name = "bike"];</code>
     */
    public Builder mergeBike(proto.abandoned_bike value) {
      if (bikeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          bike_ != null &&
          bike_ != proto.abandoned_bike.getDefaultInstance()) {
          getBikeBuilder().mergeFrom(value);
        } else {
          bike_ = value;
        }
      } else {
        bikeBuilder_.mergeFrom(value);
      }
      if (bike_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.abandoned_bike bike = 2 [json_name = "bike"];</code>
     */
    public Builder clearBike() {
      bitField0_ = (bitField0_ & ~0x00000002);
      bike_ = null;
      if (bikeBuilder_ != null) {
        bikeBuilder_.dispose();
        bikeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.abandoned_bike bike = 2 [json_name = "bike"];</code>
     */
    public proto.abandoned_bike.Builder getBikeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getBikeFieldBuilder().getBuilder();
    }
    /**
     * <code>.abandoned_bike bike = 2 [json_name = "bike"];</code>
     */
    public proto.abandoned_bikeOrBuilder getBikeOrBuilder() {
      if (bikeBuilder_ != null) {
        return bikeBuilder_.getMessageOrBuilder();
      } else {
        return bike_ == null ?
            proto.abandoned_bike.getDefaultInstance() : bike_;
      }
    }
    /**
     * <code>.abandoned_bike bike = 2 [json_name = "bike"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        proto.abandoned_bike, proto.abandoned_bike.Builder, proto.abandoned_bikeOrBuilder> 
        getBikeFieldBuilder() {
      if (bikeBuilder_ == null) {
        bikeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            proto.abandoned_bike, proto.abandoned_bike.Builder, proto.abandoned_bikeOrBuilder>(
                getBike(),
                getParentForChildren(),
                isClean());
        bike_ = null;
      }
      return bikeBuilder_;
    }

    private user_identification user_;
    private com.google.protobuf.SingleFieldBuilder<
        user_identification, user_identification.Builder, user_identificationOrBuilder> userBuilder_;
    /**
     * <code>.user_identification user = 3 [json_name = "user"];</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.user_identification user = 3 [json_name = "user"];</code>
     * @return The user.
     */
    public user_identification getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? user_identification.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.user_identification user = 3 [json_name = "user"];</code>
     */
    public Builder setUser(user_identification value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
      } else {
        userBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.user_identification user = 3 [json_name = "user"];</code>
     */
    public Builder setUser(
        user_identification.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.user_identification user = 3 [json_name = "user"];</code>
     */
    public Builder mergeUser(user_identification value) {
      if (userBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          user_ != null &&
          user_ != user_identification.getDefaultInstance()) {
          getUserBuilder().mergeFrom(value);
        } else {
          user_ = value;
        }
      } else {
        userBuilder_.mergeFrom(value);
      }
      if (user_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.user_identification user = 3 [json_name = "user"];</code>
     */
    public Builder clearUser() {
      bitField0_ = (bitField0_ & ~0x00000004);
      user_ = null;
      if (userBuilder_ != null) {
        userBuilder_.dispose();
        userBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.user_identification user = 3 [json_name = "user"];</code>
     */
    public user_identification.Builder getUserBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.user_identification user = 3 [json_name = "user"];</code>
     */
    public user_identificationOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            user_identification.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.user_identification user = 3 [json_name = "user"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        user_identification, user_identification.Builder, user_identificationOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            user_identification, user_identification.Builder, user_identificationOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:bike_abandoned)
  }

  // @@protoc_insertion_point(class_scope:bike_abandoned)
  private static final proto.bike_abandoned DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.bike_abandoned();
  }

  public static proto.bike_abandoned getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<bike_abandoned>
      PARSER = new com.google.protobuf.AbstractParser<bike_abandoned>() {
    @java.lang.Override
    public bike_abandoned parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<bike_abandoned> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<bike_abandoned> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.bike_abandoned getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

