// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_abandoned.proto
// Protobuf Java Version: 4.26.1

package proto;

public final class BikeAbandonedProto {
  private BikeAbandonedProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      BikeAbandonedProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bike_abandoned_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bike_abandoned_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_abandoned_bike_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_abandoned_bike_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032bikes/bike_abandoned.proto\032\037bikes/bike" +
      "_identification.proto\032\037users/user_identi" +
      "fication.proto\032\025common/location.proto\032\037g" +
      "oogle/protobuf/timestamp.proto\"\232\001\n\016bike_" +
      "abandoned\0229\n\ntime_stamp\030\001 \001(\0132\032.google.p" +
      "rotobuf.TimestampR\ttimeStamp\022#\n\004bike\030\002 \001" +
      "(\0132\017.abandoned_bikeR\004bike\022(\n\004user\030\003 \001(\0132" +
      "\024.user_identificationR\004user\"a\n\016abandoned" +
      "_bike\022(\n\004bike\030\001 \001(\0132\024.bike_identificatio" +
      "nR\004bike\022%\n\010location\030\002 \001(\0132\t.locationR\010lo" +
      "cationB;\n\005protoB\022BikeAbandonedProtoP\001Z\034s" +
      "tage2024/pkg/protogen/bikesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          BikeIdentificationProto.getDescriptor(),
          UserIdentificationProto.getDescriptor(),
          LocationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_bike_abandoned_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bike_abandoned_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bike_abandoned_descriptor,
        new java.lang.String[] { "TimeStamp", "Bike", "User", });
    internal_static_abandoned_bike_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_abandoned_bike_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_abandoned_bike_descriptor,
        new java.lang.String[] { "Bike", "Location", });
    descriptor.resolveAllFeaturesImmutable();
    BikeIdentificationProto.getDescriptor();
    UserIdentificationProto.getDescriptor();
    LocationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
