// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: stalling/gent.proto

package stalling

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeoPoint2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lon float64 `protobuf:"fixed64,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat float64 `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
}

func (x *GeoPoint2) Reset() {
	*x = GeoPoint2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stalling_gent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoPoint2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoPoint2) ProtoMessage() {}

func (x *GeoPoint2) ProtoReflect() protoreflect.Message {
	mi := &file_stalling_gent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoPoint2.ProtoReflect.Descriptor instead.
func (*GeoPoint2) Descriptor() ([]byte, []int) {
	return file_stalling_gent_proto_rawDescGZIP(), []int{0}
}

func (x *GeoPoint2) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GeoPoint2) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

type GentStallingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time           string     `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Facilityname   string     `protobuf:"bytes,2,opt,name=facilityname,proto3" json:"facilityname,omitempty"`
	Id             string     `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Totalplaces    int32      `protobuf:"varint,4,opt,name=totalplaces,proto3" json:"totalplaces,omitempty"`
	Freeplaces     int32      `protobuf:"varint,5,opt,name=freeplaces,proto3" json:"freeplaces,omitempty"`
	Occupiedplaces int32      `protobuf:"varint,6,opt,name=occupiedplaces,proto3" json:"occupiedplaces,omitempty"`
	Bezetting      int32      `protobuf:"varint,7,opt,name=bezetting,proto3" json:"bezetting,omitempty"`
	GeoPoint_2D    *GeoPoint2 `protobuf:"bytes,8,opt,name=geo_point_2d,json=geoPoint2d,proto3" json:"geo_point_2d,omitempty"`
}

func (x *GentStallingInfo) Reset() {
	*x = GentStallingInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stalling_gent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GentStallingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GentStallingInfo) ProtoMessage() {}

func (x *GentStallingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stalling_gent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GentStallingInfo.ProtoReflect.Descriptor instead.
func (*GentStallingInfo) Descriptor() ([]byte, []int) {
	return file_stalling_gent_proto_rawDescGZIP(), []int{1}
}

func (x *GentStallingInfo) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *GentStallingInfo) GetFacilityname() string {
	if x != nil {
		return x.Facilityname
	}
	return ""
}

func (x *GentStallingInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GentStallingInfo) GetTotalplaces() int32 {
	if x != nil {
		return x.Totalplaces
	}
	return 0
}

func (x *GentStallingInfo) GetFreeplaces() int32 {
	if x != nil {
		return x.Freeplaces
	}
	return 0
}

func (x *GentStallingInfo) GetOccupiedplaces() int32 {
	if x != nil {
		return x.Occupiedplaces
	}
	return 0
}

func (x *GentStallingInfo) GetBezetting() int32 {
	if x != nil {
		return x.Bezetting
	}
	return 0
}

func (x *GentStallingInfo) GetGeoPoint_2D() *GeoPoint2 {
	if x != nil {
		return x.GeoPoint_2D
	}
	return nil
}

var File_stalling_gent_proto protoreflect.FileDescriptor

var file_stalling_gent_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x09, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x22, 0x90, 0x02, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x66, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x72, 0x65, 0x65, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x72, 0x65, 0x65, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65,
	0x64, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6f,
	0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x62, 0x65, 0x7a, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x62, 0x65, 0x7a, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x2c, 0x0a, 0x0c, 0x67,
	0x65, 0x6f, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x32, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x52, 0x0a, 0x67,
	0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x64, 0x42, 0x2e, 0x42, 0x09, 0x47, 0x65, 0x6e,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x32,
	0x30, 0x32, 0x34, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e,
	0x2f, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_stalling_gent_proto_rawDescOnce sync.Once
	file_stalling_gent_proto_rawDescData = file_stalling_gent_proto_rawDesc
)

func file_stalling_gent_proto_rawDescGZIP() []byte {
	file_stalling_gent_proto_rawDescOnce.Do(func() {
		file_stalling_gent_proto_rawDescData = protoimpl.X.CompressGZIP(file_stalling_gent_proto_rawDescData)
	})
	return file_stalling_gent_proto_rawDescData
}

var file_stalling_gent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stalling_gent_proto_goTypes = []interface{}{
	(*GeoPoint2)(nil),        // 0: GeoPoint2
	(*GentStallingInfo)(nil), // 1: GentStallingInfo
}
var file_stalling_gent_proto_depIdxs = []int32{
	0, // 0: GentStallingInfo.geo_point_2d:type_name -> GeoPoint2
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stalling_gent_proto_init() }
func file_stalling_gent_proto_init() {
	if File_stalling_gent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stalling_gent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeoPoint2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stalling_gent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GentStallingInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stalling_gent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stalling_gent_proto_goTypes,
		DependencyIndexes: file_stalling_gent_proto_depIdxs,
		MessageInfos:      file_stalling_gent_proto_msgTypes,
	}.Build()
	File_stalling_gent_proto = out.File
	file_stalling_gent_proto_rawDesc = nil
	file_stalling_gent_proto_goTypes = nil
	file_stalling_gent_proto_depIdxs = nil
}
