// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: bike.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lon float64 `protobuf:"fixed64,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat float64 `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

type Bike struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BikeId             string    `protobuf:"bytes,1,opt,name=bike_id,json=bikeId,proto3" json:"bike_id,omitempty"`
	Lat                float64   `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                float64   `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	CurrentRangeMeters int32     `protobuf:"varint,4,opt,name=current_range_meters,json=currentRangeMeters,proto3" json:"current_range_meters,omitempty"`
	PricingPlanId      string    `protobuf:"bytes,5,opt,name=pricing_plan_id,json=pricingPlanId,proto3" json:"pricing_plan_id,omitempty"`
	VehicleTypeId      string    `protobuf:"bytes,6,opt,name=vehicle_type_id,json=vehicleTypeId,proto3" json:"vehicle_type_id,omitempty"`
	IsReserved         int32     `protobuf:"varint,7,opt,name=is_reserved,json=isReserved,proto3" json:"is_reserved,omitempty"`
	IsDisabled         int32     `protobuf:"varint,8,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`
	RentalUris         string    `protobuf:"bytes,9,opt,name=rental_uris,json=rentalUris,proto3" json:"rental_uris,omitempty"`
	Loc                *Location `protobuf:"bytes,10,opt,name=loc,proto3" json:"loc,omitempty"`
}

func (x *Bike) Reset() {
	*x = Bike{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bike) ProtoMessage() {}

func (x *Bike) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bike.ProtoReflect.Descriptor instead.
func (*Bike) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{1}
}

func (x *Bike) GetBikeId() string {
	if x != nil {
		return x.BikeId
	}
	return ""
}

func (x *Bike) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Bike) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Bike) GetCurrentRangeMeters() int32 {
	if x != nil {
		return x.CurrentRangeMeters
	}
	return 0
}

func (x *Bike) GetPricingPlanId() string {
	if x != nil {
		return x.PricingPlanId
	}
	return ""
}

func (x *Bike) GetVehicleTypeId() string {
	if x != nil {
		return x.VehicleTypeId
	}
	return ""
}

func (x *Bike) GetIsReserved() int32 {
	if x != nil {
		return x.IsReserved
	}
	return 0
}

func (x *Bike) GetIsDisabled() int32 {
	if x != nil {
		return x.IsDisabled
	}
	return 0
}

func (x *Bike) GetRentalUris() string {
	if x != nil {
		return x.RentalUris
	}
	return ""
}

func (x *Bike) GetLoc() *Location {
	if x != nil {
		return x.Loc
	}
	return nil
}

var File_bike_proto protoreflect.FileDescriptor

var file_bike_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x69, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x08,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x22, 0xc5, 0x02, 0x0a,
	0x04, 0x42, 0x69, 0x6b, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x69, 0x6b, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x69, 0x6b, 0x65, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c,
	0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x14, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x12, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x5f,
	0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70,
	0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x50, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f,
	0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x73, 0x52, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x73, 0x44, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x5f, 0x75, 0x72, 0x69, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x55, 0x72, 0x69, 0x73, 0x12, 0x1b, 0x0a, 0x03, 0x6c, 0x6f, 0x63, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x03, 0x6c, 0x6f, 0x63, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bike_proto_rawDescOnce sync.Once
	file_bike_proto_rawDescData = file_bike_proto_rawDesc
)

func file_bike_proto_rawDescGZIP() []byte {
	file_bike_proto_rawDescOnce.Do(func() {
		file_bike_proto_rawDescData = protoimpl.X.CompressGZIP(file_bike_proto_rawDescData)
	})
	return file_bike_proto_rawDescData
}

var file_bike_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bike_proto_goTypes = []interface{}{
	(*Location)(nil), // 0: Location
	(*Bike)(nil),     // 1: Bike
}
var file_bike_proto_depIdxs = []int32{
	0, // 0: Bike.loc:type_name -> Location
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bike_proto_init() }
func file_bike_proto_init() {
	if File_bike_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bike_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bike); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bike_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bike_proto_goTypes,
		DependencyIndexes: file_bike_proto_depIdxs,
		MessageInfos:      file_bike_proto_msgTypes,
	}.Build()
	File_bike_proto = out.File
	file_bike_proto_rawDesc = nil
	file_bike_proto_goTypes = nil
	file_bike_proto_depIdxs = nil
}
