// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: bikes/bike_identification.proto

package bikes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BikeIdentification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // uuid
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *BikeIdentification) Reset() {
	*x = BikeIdentification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bikes_bike_identification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BikeIdentification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BikeIdentification) ProtoMessage() {}

func (x *BikeIdentification) ProtoReflect() protoreflect.Message {
	mi := &file_bikes_bike_identification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BikeIdentification.ProtoReflect.Descriptor instead.
func (*BikeIdentification) Descriptor() ([]byte, []int) {
	return file_bikes_bike_identification_proto_rawDescGZIP(), []int{0}
}

func (x *BikeIdentification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BikeIdentification) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_bikes_bike_identification_proto protoreflect.FileDescriptor

var file_bikes_bike_identification_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x2f, 0x62, 0x69, 0x6b, 0x65, 0x5f, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3b, 0x0a, 0x13, 0x62, 0x69, 0x6b, 0x65, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x39,
	0x42, 0x17, 0x42, 0x69, 0x6b, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1c, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x32, 0x30, 0x32, 0x34, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x67, 0x65, 0x6e, 0x2f, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_bikes_bike_identification_proto_rawDescOnce sync.Once
	file_bikes_bike_identification_proto_rawDescData = file_bikes_bike_identification_proto_rawDesc
)

func file_bikes_bike_identification_proto_rawDescGZIP() []byte {
	file_bikes_bike_identification_proto_rawDescOnce.Do(func() {
		file_bikes_bike_identification_proto_rawDescData = protoimpl.X.CompressGZIP(file_bikes_bike_identification_proto_rawDescData)
	})
	return file_bikes_bike_identification_proto_rawDescData
}

var file_bikes_bike_identification_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bikes_bike_identification_proto_goTypes = []interface{}{
	(*BikeIdentification)(nil), // 0: bike_identification
}
var file_bikes_bike_identification_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bikes_bike_identification_proto_init() }
func file_bikes_bike_identification_proto_init() {
	if File_bikes_bike_identification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bikes_bike_identification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BikeIdentification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bikes_bike_identification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bikes_bike_identification_proto_goTypes,
		DependencyIndexes: file_bikes_bike_identification_proto_depIdxs,
		MessageInfos:      file_bikes_bike_identification_proto_msgTypes,
	}.Build()
	File_bikes_bike_identification_proto = out.File
	file_bikes_bike_identification_proto_rawDesc = nil
	file_bikes_bike_identification_proto_goTypes = nil
	file_bikes_bike_identification_proto_depIdxs = nil
}
