---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-gen
  template:
    metadata:
      labels:
        app: event-gen
    spec:
      containers:
        - name: event-gen
          image: "ghcr.io/julesrosier/stage-2024:latest"
          imagePullPolicy: Always
          env:
            - name: DB_DATABASE_OLTP
              value: gen_oltp
            - name: DB_HOST
              value: "10.51.75.38"
            - name: DB_PASSWORD
              value: SecurePassword
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: ps_user
            - name: LOG_LEVEL
              value: DEBUG
            - name: REGISTRY
              value: redpanda-0.redpanda.redpanda.svc.cluster.local:8081
            - name: SEED_BROKER
              value: redpanda-0.redpanda.redpanda.svc.cluster.local:9093
            - name: EH_AUTH_USER
              value: superuser
            - name: EH_AUTH_PASSWORD
              value: secretpassword
