---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-gen
data:
  config.yaml: |
    logger:
      level: DEBUG
    database:
      user: ps_user
      password: SecurePassword
      database: gen_oltp
      host: postgres
      port: 5432
    kafka:
      brokers:
        - redpanda-0.redpanda.redpanda.svc.cluster.local:9093
        - redpanda-1.redpanda.redpanda.svc.cluster.local:9093
        - redpanda-2.redpanda.redpanda.svc.cluster.local:9093
      schemaRegistry:
        urls:
          - redpanda-0.redpanda.redpanda.svc.cluster.local:8081
          - redpanda-1.redpanda.redpanda.svc.cluster.local:8081
          - redpanda-2.redpanda.redpanda.svc.cluster.local:8081
      auth:
        user: superuser
        password: secretpassword
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-gen
  template:
    metadata:
      labels:
        app: event-gen
    spec:
      containers:
        - name: event-gen
          image: "ghcr.io/julesrosier/stage-2024:latest"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/config
              name: configs
              readOnly: true
      volumes:
        - name: configs
          configMap:
            defaultMode: 420
            name: event-gen
