// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_stored.proto
// Protobuf Java Version: 4.26.1

public final class BikeStoredProto {
  private BikeStoredProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      BikeStoredProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bike_stored_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bike_stored_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027bikes/bike_stored.proto\032\037google/protob" +
      "uf/timestamp.proto\032\037bikes/bike_identific" +
      "ation.proto\"r\n\013bike_stored\0229\n\ntime_stamp" +
      "\030\001 \001(\0132\032.google.protobuf.TimestampR\ttime" +
      "Stamp\022(\n\004bike\030\002 \001(\0132\024.bike_identificatio" +
      "nR\004bikeB1B\017BikeStoredProtoP\001Z\034stage2024/" +
      "pkg/protogen/bikesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          BikeIdentificationProto.getDescriptor(),
        });
    internal_static_bike_stored_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bike_stored_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bike_stored_descriptor,
        new java.lang.String[] { "TimeStamp", "Bike", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    BikeIdentificationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
