// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_reserved.proto

// Protobuf Java Version: 4.26.1
public interface bikeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bike)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
   * @return Whether the bike field is set.
   */
  boolean hasBike();
  /**
   * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
   * @return The bike.
   */
  bike_identification getBike();
  /**
   * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
   */
  bike_identificationOrBuilder getBikeOrBuilder();

  /**
   * <code>bool is_electric = 2 [json_name = "isElectric"];</code>
   * @return The isElectric.
   */
  boolean getIsElectric();
}
