// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_immobilized.proto
// Protobuf Java Version: 4.26.1

public final class BikeImmobilizedProto {
  private BikeImmobilizedProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      BikeImmobilizedProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bike_immobilized_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bike_immobilized_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_location_bike_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_location_bike_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034bikes/bike_immobilized.proto\032\037google/p" +
      "rotobuf/timestamp.proto\032\037bikes/bike_iden" +
      "tification.proto\032\025common/location.proto\"" +
      "q\n\020bike_immobilized\0229\n\ntime_stamp\030\001 \001(\0132" +
      "\032.google.protobuf.TimestampR\ttimeStamp\022\"" +
      "\n\004bike\030\002 \001(\0132\016.location_bikeR\004bike\"`\n\rlo" +
      "cation_bike\022(\n\004bike\030\001 \001(\0132\024.bike_identif" +
      "icationR\004bike\022%\n\010location\030\002 \001(\0132\t.locati" +
      "onR\010locationB6B\024BikeImmobilizedProtoP\001Z\034" +
      "stage2024/pkg/protogen/bikesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          BikeIdentificationProto.getDescriptor(),
          LocationProto.getDescriptor(),
        });
    internal_static_bike_immobilized_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bike_immobilized_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bike_immobilized_descriptor,
        new java.lang.String[] { "TimeStamp", "Bike", });
    internal_static_location_bike_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_location_bike_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_location_bike_descriptor,
        new java.lang.String[] { "Bike", "Location", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    BikeIdentificationProto.getDescriptor();
    LocationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
