// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_defect_reported.proto

// Protobuf Java Version: 4.26.1
public interface bike_defect_reportedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bike_defect_reported)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return Whether the timeStamp field is set.
   */
  boolean hasTimeStamp();
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return The timeStamp.
   */
  com.google.protobuf.Timestamp getTimeStamp();
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder();

  /**
   * <code>.defect_bike bike = 2 [json_name = "bike"];</code>
   * @return Whether the bike field is set.
   */
  boolean hasBike();
  /**
   * <code>.defect_bike bike = 2 [json_name = "bike"];</code>
   * @return The bike.
   */
  defect_bike getBike();
  /**
   * <code>.defect_bike bike = 2 [json_name = "bike"];</code>
   */
  defect_bikeOrBuilder getBikeOrBuilder();

  /**
   * <code>.user_identification user = 3 [json_name = "user"];</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.user_identification user = 3 [json_name = "user"];</code>
   * @return The user.
   */
  user_identification getUser();
  /**
   * <code>.user_identification user = 3 [json_name = "user"];</code>
   */
  user_identificationOrBuilder getUserOrBuilder();

  /**
   * <code>string reported_defect = 4 [json_name = "reportedDefect"];</code>
   * @return The reportedDefect.
   */
  java.lang.String getReportedDefect();
  /**
   * <code>string reported_defect = 4 [json_name = "reportedDefect"];</code>
   * @return The bytes for reportedDefect.
   */
  com.google.protobuf.ByteString
      getReportedDefectBytes();
}
