// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_picked_up.proto
// Protobuf Java Version: 4.26.1

public final class BikePickedUpProto {
  private BikePickedUpProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      BikePickedUpProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bike_picked_up_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bike_picked_up_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032bikes/bike_picked_up.proto\032\037google/pro" +
      "tobuf/timestamp.proto\032\037bikes/bike_identi" +
      "fication.proto\032%stations/station_identif" +
      "ication.proto\032\037users/user_identification" +
      ".proto\"\322\001\n\016bike_picked_up\0229\n\ntime_stamp\030" +
      "\001 \001(\0132\032.google.protobuf.TimestampR\ttimeS" +
      "tamp\022(\n\004bike\030\002 \001(\0132\024.bike_identification" +
      "R\004bike\0221\n\007station\030\003 \001(\0132\027.station_identi" +
      "ficationR\007station\022(\n\004user\030\004 \001(\0132\024.user_i" +
      "dentificationR\004userB3B\021BikePickedUpProto" +
      "P\001Z\034stage2024/pkg/protogen/bikesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          BikeIdentificationProto.getDescriptor(),
          StationIdentificationProto.getDescriptor(),
          UserIdentificationProto.getDescriptor(),
        });
    internal_static_bike_picked_up_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bike_picked_up_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bike_picked_up_descriptor,
        new java.lang.String[] { "TimeStamp", "Bike", "Station", "User", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    BikeIdentificationProto.getDescriptor();
    StationIdentificationProto.getDescriptor();
    UserIdentificationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
