// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_returned.proto

// Protobuf Java Version: 4.26.1
public interface bike_returnedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bike_returned)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return Whether the timeStamp field is set.
   */
  boolean hasTimeStamp();
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return The timeStamp.
   */
  com.google.protobuf.Timestamp getTimeStamp();
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder();

  /**
   * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
   * @return Whether the bike field is set.
   */
  boolean hasBike();
  /**
   * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
   * @return The bike.
   */
  bike_identification getBike();
  /**
   * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
   */
  bike_identificationOrBuilder getBikeOrBuilder();

  /**
   * <code>.station_identification station = 3 [json_name = "station"];</code>
   * @return Whether the station field is set.
   */
  boolean hasStation();
  /**
   * <code>.station_identification station = 3 [json_name = "station"];</code>
   * @return The station.
   */
  station_identification getStation();
  /**
   * <code>.station_identification station = 3 [json_name = "station"];</code>
   */
  station_identificationOrBuilder getStationOrBuilder();

  /**
   * <code>.user_identification user = 4 [json_name = "user"];</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.user_identification user = 4 [json_name = "user"];</code>
   * @return The user.
   */
  user_identification getUser();
  /**
   * <code>.user_identification user = 4 [json_name = "user"];</code>
   */
  user_identificationOrBuilder getUserOrBuilder();
}
