// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_picked_up.proto

// Protobuf Java Version: 4.26.1
/**
 * Protobuf type {@code bike_picked_up}
 */
public final class bike_picked_up extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bike_picked_up)
    bike_picked_upOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      bike_picked_up.class.getName());
  }
  // Use bike_picked_up.newBuilder() to construct.
  private bike_picked_up(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private bike_picked_up() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BikePickedUpProto.internal_static_bike_picked_up_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BikePickedUpProto.internal_static_bike_picked_up_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bike_picked_up.class, bike_picked_up.Builder.class);
  }

  private int bitField0_;
  public static final int TIME_STAMP_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp timeStamp_;
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return Whether the timeStamp field is set.
   */
  @java.lang.Override
  public boolean hasTimeStamp() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return The timeStamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimeStamp() {
    return timeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder() {
    return timeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
  }

  public static final int BIKE_FIELD_NUMBER = 2;
  private bike_identification bike_;
  /**
   * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
   * @return Whether the bike field is set.
   */
  @java.lang.Override
  public boolean hasBike() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
   * @return The bike.
   */
  @java.lang.Override
  public bike_identification getBike() {
    return bike_ == null ? bike_identification.getDefaultInstance() : bike_;
  }
  /**
   * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
   */
  @java.lang.Override
  public bike_identificationOrBuilder getBikeOrBuilder() {
    return bike_ == null ? bike_identification.getDefaultInstance() : bike_;
  }

  public static final int STATION_FIELD_NUMBER = 3;
  private station_identification station_;
  /**
   * <code>.station_identification station = 3 [json_name = "station"];</code>
   * @return Whether the station field is set.
   */
  @java.lang.Override
  public boolean hasStation() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.station_identification station = 3 [json_name = "station"];</code>
   * @return The station.
   */
  @java.lang.Override
  public station_identification getStation() {
    return station_ == null ? station_identification.getDefaultInstance() : station_;
  }
  /**
   * <code>.station_identification station = 3 [json_name = "station"];</code>
   */
  @java.lang.Override
  public station_identificationOrBuilder getStationOrBuilder() {
    return station_ == null ? station_identification.getDefaultInstance() : station_;
  }

  public static final int USER_FIELD_NUMBER = 4;
  private user_identification user_;
  /**
   * <code>.user_identification user = 4 [json_name = "user"];</code>
   * @return Whether the user field is set.
   */
  @java.lang.Override
  public boolean hasUser() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.user_identification user = 4 [json_name = "user"];</code>
   * @return The user.
   */
  @java.lang.Override
  public user_identification getUser() {
    return user_ == null ? user_identification.getDefaultInstance() : user_;
  }
  /**
   * <code>.user_identification user = 4 [json_name = "user"];</code>
   */
  @java.lang.Override
  public user_identificationOrBuilder getUserOrBuilder() {
    return user_ == null ? user_identification.getDefaultInstance() : user_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getTimeStamp());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getBike());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getStation());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getUser());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTimeStamp());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBike());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getStation());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUser());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bike_picked_up)) {
      return super.equals(obj);
    }
    bike_picked_up other = (bike_picked_up) obj;

    if (hasTimeStamp() != other.hasTimeStamp()) return false;
    if (hasTimeStamp()) {
      if (!getTimeStamp()
          .equals(other.getTimeStamp())) return false;
    }
    if (hasBike() != other.hasBike()) return false;
    if (hasBike()) {
      if (!getBike()
          .equals(other.getBike())) return false;
    }
    if (hasStation() != other.hasStation()) return false;
    if (hasStation()) {
      if (!getStation()
          .equals(other.getStation())) return false;
    }
    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTimeStamp()) {
      hash = (37 * hash) + TIME_STAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
    }
    if (hasBike()) {
      hash = (37 * hash) + BIKE_FIELD_NUMBER;
      hash = (53 * hash) + getBike().hashCode();
    }
    if (hasStation()) {
      hash = (37 * hash) + STATION_FIELD_NUMBER;
      hash = (53 * hash) + getStation().hashCode();
    }
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bike_picked_up parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bike_picked_up parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bike_picked_up parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bike_picked_up parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bike_picked_up parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bike_picked_up parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bike_picked_up parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bike_picked_up parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static bike_picked_up parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static bike_picked_up parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bike_picked_up parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bike_picked_up parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bike_picked_up prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bike_picked_up}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bike_picked_up)
      bike_picked_upOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BikePickedUpProto.internal_static_bike_picked_up_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BikePickedUpProto.internal_static_bike_picked_up_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bike_picked_up.class, bike_picked_up.Builder.class);
    }

    // Construct using bike_picked_up.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getTimeStampFieldBuilder();
        getBikeFieldBuilder();
        getStationFieldBuilder();
        getUserFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      bike_ = null;
      if (bikeBuilder_ != null) {
        bikeBuilder_.dispose();
        bikeBuilder_ = null;
      }
      station_ = null;
      if (stationBuilder_ != null) {
        stationBuilder_.dispose();
        stationBuilder_ = null;
      }
      user_ = null;
      if (userBuilder_ != null) {
        userBuilder_.dispose();
        userBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BikePickedUpProto.internal_static_bike_picked_up_descriptor;
    }

    @java.lang.Override
    public bike_picked_up getDefaultInstanceForType() {
      return bike_picked_up.getDefaultInstance();
    }

    @java.lang.Override
    public bike_picked_up build() {
      bike_picked_up result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bike_picked_up buildPartial() {
      bike_picked_up result = new bike_picked_up(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(bike_picked_up result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.timeStamp_ = timeStampBuilder_ == null
            ? timeStamp_
            : timeStampBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.bike_ = bikeBuilder_ == null
            ? bike_
            : bikeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.station_ = stationBuilder_ == null
            ? station_
            : stationBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.user_ = userBuilder_ == null
            ? user_
            : userBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bike_picked_up) {
        return mergeFrom((bike_picked_up)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bike_picked_up other) {
      if (other == bike_picked_up.getDefaultInstance()) return this;
      if (other.hasTimeStamp()) {
        mergeTimeStamp(other.getTimeStamp());
      }
      if (other.hasBike()) {
        mergeBike(other.getBike());
      }
      if (other.hasStation()) {
        mergeStation(other.getStation());
      }
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTimeStampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getBikeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getStationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getUserFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Timestamp timeStamp_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeStampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     * @return Whether the timeStamp field is set.
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     * @return The timeStamp.
     */
    public com.google.protobuf.Timestamp getTimeStamp() {
      if (timeStampBuilder_ == null) {
        return timeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
      } else {
        return timeStampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public Builder setTimeStamp(com.google.protobuf.Timestamp value) {
      if (timeStampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeStamp_ = value;
      } else {
        timeStampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public Builder setTimeStamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timeStampBuilder_ == null) {
        timeStamp_ = builderForValue.build();
      } else {
        timeStampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public Builder mergeTimeStamp(com.google.protobuf.Timestamp value) {
      if (timeStampBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          timeStamp_ != null &&
          timeStamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimeStampBuilder().mergeFrom(value);
        } else {
          timeStamp_ = value;
        }
      } else {
        timeStampBuilder_.mergeFrom(value);
      }
      if (timeStamp_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public Builder clearTimeStamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimeStampBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTimeStampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder() {
      if (timeStampBuilder_ != null) {
        return timeStampBuilder_.getMessageOrBuilder();
      } else {
        return timeStamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimeStampFieldBuilder() {
      if (timeStampBuilder_ == null) {
        timeStampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimeStamp(),
                getParentForChildren(),
                isClean());
        timeStamp_ = null;
      }
      return timeStampBuilder_;
    }

    private bike_identification bike_;
    private com.google.protobuf.SingleFieldBuilder<
        bike_identification, bike_identification.Builder, bike_identificationOrBuilder> bikeBuilder_;
    /**
     * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
     * @return Whether the bike field is set.
     */
    public boolean hasBike() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
     * @return The bike.
     */
    public bike_identification getBike() {
      if (bikeBuilder_ == null) {
        return bike_ == null ? bike_identification.getDefaultInstance() : bike_;
      } else {
        return bikeBuilder_.getMessage();
      }
    }
    /**
     * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
     */
    public Builder setBike(bike_identification value) {
      if (bikeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bike_ = value;
      } else {
        bikeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
     */
    public Builder setBike(
        bike_identification.Builder builderForValue) {
      if (bikeBuilder_ == null) {
        bike_ = builderForValue.build();
      } else {
        bikeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
     */
    public Builder mergeBike(bike_identification value) {
      if (bikeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          bike_ != null &&
          bike_ != bike_identification.getDefaultInstance()) {
          getBikeBuilder().mergeFrom(value);
        } else {
          bike_ = value;
        }
      } else {
        bikeBuilder_.mergeFrom(value);
      }
      if (bike_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
     */
    public Builder clearBike() {
      bitField0_ = (bitField0_ & ~0x00000002);
      bike_ = null;
      if (bikeBuilder_ != null) {
        bikeBuilder_.dispose();
        bikeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
     */
    public bike_identification.Builder getBikeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getBikeFieldBuilder().getBuilder();
    }
    /**
     * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
     */
    public bike_identificationOrBuilder getBikeOrBuilder() {
      if (bikeBuilder_ != null) {
        return bikeBuilder_.getMessageOrBuilder();
      } else {
        return bike_ == null ?
            bike_identification.getDefaultInstance() : bike_;
      }
    }
    /**
     * <code>.bike_identification bike = 2 [json_name = "bike"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        bike_identification, bike_identification.Builder, bike_identificationOrBuilder> 
        getBikeFieldBuilder() {
      if (bikeBuilder_ == null) {
        bikeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            bike_identification, bike_identification.Builder, bike_identificationOrBuilder>(
                getBike(),
                getParentForChildren(),
                isClean());
        bike_ = null;
      }
      return bikeBuilder_;
    }

    private station_identification station_;
    private com.google.protobuf.SingleFieldBuilder<
        station_identification, station_identification.Builder, station_identificationOrBuilder> stationBuilder_;
    /**
     * <code>.station_identification station = 3 [json_name = "station"];</code>
     * @return Whether the station field is set.
     */
    public boolean hasStation() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.station_identification station = 3 [json_name = "station"];</code>
     * @return The station.
     */
    public station_identification getStation() {
      if (stationBuilder_ == null) {
        return station_ == null ? station_identification.getDefaultInstance() : station_;
      } else {
        return stationBuilder_.getMessage();
      }
    }
    /**
     * <code>.station_identification station = 3 [json_name = "station"];</code>
     */
    public Builder setStation(station_identification value) {
      if (stationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        station_ = value;
      } else {
        stationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.station_identification station = 3 [json_name = "station"];</code>
     */
    public Builder setStation(
        station_identification.Builder builderForValue) {
      if (stationBuilder_ == null) {
        station_ = builderForValue.build();
      } else {
        stationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.station_identification station = 3 [json_name = "station"];</code>
     */
    public Builder mergeStation(station_identification value) {
      if (stationBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          station_ != null &&
          station_ != station_identification.getDefaultInstance()) {
          getStationBuilder().mergeFrom(value);
        } else {
          station_ = value;
        }
      } else {
        stationBuilder_.mergeFrom(value);
      }
      if (station_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.station_identification station = 3 [json_name = "station"];</code>
     */
    public Builder clearStation() {
      bitField0_ = (bitField0_ & ~0x00000004);
      station_ = null;
      if (stationBuilder_ != null) {
        stationBuilder_.dispose();
        stationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.station_identification station = 3 [json_name = "station"];</code>
     */
    public station_identification.Builder getStationBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getStationFieldBuilder().getBuilder();
    }
    /**
     * <code>.station_identification station = 3 [json_name = "station"];</code>
     */
    public station_identificationOrBuilder getStationOrBuilder() {
      if (stationBuilder_ != null) {
        return stationBuilder_.getMessageOrBuilder();
      } else {
        return station_ == null ?
            station_identification.getDefaultInstance() : station_;
      }
    }
    /**
     * <code>.station_identification station = 3 [json_name = "station"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        station_identification, station_identification.Builder, station_identificationOrBuilder> 
        getStationFieldBuilder() {
      if (stationBuilder_ == null) {
        stationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            station_identification, station_identification.Builder, station_identificationOrBuilder>(
                getStation(),
                getParentForChildren(),
                isClean());
        station_ = null;
      }
      return stationBuilder_;
    }

    private user_identification user_;
    private com.google.protobuf.SingleFieldBuilder<
        user_identification, user_identification.Builder, user_identificationOrBuilder> userBuilder_;
    /**
     * <code>.user_identification user = 4 [json_name = "user"];</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.user_identification user = 4 [json_name = "user"];</code>
     * @return The user.
     */
    public user_identification getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? user_identification.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.user_identification user = 4 [json_name = "user"];</code>
     */
    public Builder setUser(user_identification value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
      } else {
        userBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.user_identification user = 4 [json_name = "user"];</code>
     */
    public Builder setUser(
        user_identification.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.user_identification user = 4 [json_name = "user"];</code>
     */
    public Builder mergeUser(user_identification value) {
      if (userBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          user_ != null &&
          user_ != user_identification.getDefaultInstance()) {
          getUserBuilder().mergeFrom(value);
        } else {
          user_ = value;
        }
      } else {
        userBuilder_.mergeFrom(value);
      }
      if (user_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.user_identification user = 4 [json_name = "user"];</code>
     */
    public Builder clearUser() {
      bitField0_ = (bitField0_ & ~0x00000008);
      user_ = null;
      if (userBuilder_ != null) {
        userBuilder_.dispose();
        userBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.user_identification user = 4 [json_name = "user"];</code>
     */
    public user_identification.Builder getUserBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.user_identification user = 4 [json_name = "user"];</code>
     */
    public user_identificationOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            user_identification.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.user_identification user = 4 [json_name = "user"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        user_identification, user_identification.Builder, user_identificationOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            user_identification, user_identification.Builder, user_identificationOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:bike_picked_up)
  }

  // @@protoc_insertion_point(class_scope:bike_picked_up)
  private static final bike_picked_up DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bike_picked_up();
  }

  public static bike_picked_up getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<bike_picked_up>
      PARSER = new com.google.protobuf.AbstractParser<bike_picked_up>() {
    @java.lang.Override
    public bike_picked_up parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<bike_picked_up> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<bike_picked_up> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bike_picked_up getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

