// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_reserved.proto

// Protobuf Java Version: 4.26.1
/**
 * Protobuf type {@code bike}
 */
public final class bike extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bike)
    bikeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      bike.class.getName());
  }
  // Use bike.newBuilder() to construct.
  private bike(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private bike() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BikeReservedProto.internal_static_bike_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BikeReservedProto.internal_static_bike_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bike.class, bike.Builder.class);
  }

  private int bitField0_;
  public static final int BIKE_FIELD_NUMBER = 1;
  private bike_identification bike_;
  /**
   * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
   * @return Whether the bike field is set.
   */
  @java.lang.Override
  public boolean hasBike() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
   * @return The bike.
   */
  @java.lang.Override
  public bike_identification getBike() {
    return bike_ == null ? bike_identification.getDefaultInstance() : bike_;
  }
  /**
   * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
   */
  @java.lang.Override
  public bike_identificationOrBuilder getBikeOrBuilder() {
    return bike_ == null ? bike_identification.getDefaultInstance() : bike_;
  }

  public static final int IS_ELECTRIC_FIELD_NUMBER = 2;
  private boolean isElectric_ = false;
  /**
   * <code>bool is_electric = 2 [json_name = "isElectric"];</code>
   * @return The isElectric.
   */
  @java.lang.Override
  public boolean getIsElectric() {
    return isElectric_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBike());
    }
    if (isElectric_ != false) {
      output.writeBool(2, isElectric_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBike());
    }
    if (isElectric_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isElectric_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bike)) {
      return super.equals(obj);
    }
    bike other = (bike) obj;

    if (hasBike() != other.hasBike()) return false;
    if (hasBike()) {
      if (!getBike()
          .equals(other.getBike())) return false;
    }
    if (getIsElectric()
        != other.getIsElectric()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBike()) {
      hash = (37 * hash) + BIKE_FIELD_NUMBER;
      hash = (53 * hash) + getBike().hashCode();
    }
    hash = (37 * hash) + IS_ELECTRIC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsElectric());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bike parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bike parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bike parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bike parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bike parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bike parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bike parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bike parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static bike parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static bike parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bike parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bike parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bike prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bike}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bike)
      bikeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BikeReservedProto.internal_static_bike_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BikeReservedProto.internal_static_bike_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bike.class, bike.Builder.class);
    }

    // Construct using bike.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getBikeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      bike_ = null;
      if (bikeBuilder_ != null) {
        bikeBuilder_.dispose();
        bikeBuilder_ = null;
      }
      isElectric_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BikeReservedProto.internal_static_bike_descriptor;
    }

    @java.lang.Override
    public bike getDefaultInstanceForType() {
      return bike.getDefaultInstance();
    }

    @java.lang.Override
    public bike build() {
      bike result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bike buildPartial() {
      bike result = new bike(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(bike result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.bike_ = bikeBuilder_ == null
            ? bike_
            : bikeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isElectric_ = isElectric_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bike) {
        return mergeFrom((bike)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bike other) {
      if (other == bike.getDefaultInstance()) return this;
      if (other.hasBike()) {
        mergeBike(other.getBike());
      }
      if (other.getIsElectric() != false) {
        setIsElectric(other.getIsElectric());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBikeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              isElectric_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private bike_identification bike_;
    private com.google.protobuf.SingleFieldBuilder<
        bike_identification, bike_identification.Builder, bike_identificationOrBuilder> bikeBuilder_;
    /**
     * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
     * @return Whether the bike field is set.
     */
    public boolean hasBike() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
     * @return The bike.
     */
    public bike_identification getBike() {
      if (bikeBuilder_ == null) {
        return bike_ == null ? bike_identification.getDefaultInstance() : bike_;
      } else {
        return bikeBuilder_.getMessage();
      }
    }
    /**
     * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
     */
    public Builder setBike(bike_identification value) {
      if (bikeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bike_ = value;
      } else {
        bikeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
     */
    public Builder setBike(
        bike_identification.Builder builderForValue) {
      if (bikeBuilder_ == null) {
        bike_ = builderForValue.build();
      } else {
        bikeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
     */
    public Builder mergeBike(bike_identification value) {
      if (bikeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          bike_ != null &&
          bike_ != bike_identification.getDefaultInstance()) {
          getBikeBuilder().mergeFrom(value);
        } else {
          bike_ = value;
        }
      } else {
        bikeBuilder_.mergeFrom(value);
      }
      if (bike_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
     */
    public Builder clearBike() {
      bitField0_ = (bitField0_ & ~0x00000001);
      bike_ = null;
      if (bikeBuilder_ != null) {
        bikeBuilder_.dispose();
        bikeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
     */
    public bike_identification.Builder getBikeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBikeFieldBuilder().getBuilder();
    }
    /**
     * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
     */
    public bike_identificationOrBuilder getBikeOrBuilder() {
      if (bikeBuilder_ != null) {
        return bikeBuilder_.getMessageOrBuilder();
      } else {
        return bike_ == null ?
            bike_identification.getDefaultInstance() : bike_;
      }
    }
    /**
     * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        bike_identification, bike_identification.Builder, bike_identificationOrBuilder> 
        getBikeFieldBuilder() {
      if (bikeBuilder_ == null) {
        bikeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            bike_identification, bike_identification.Builder, bike_identificationOrBuilder>(
                getBike(),
                getParentForChildren(),
                isClean());
        bike_ = null;
      }
      return bikeBuilder_;
    }

    private boolean isElectric_ ;
    /**
     * <code>bool is_electric = 2 [json_name = "isElectric"];</code>
     * @return The isElectric.
     */
    @java.lang.Override
    public boolean getIsElectric() {
      return isElectric_;
    }
    /**
     * <code>bool is_electric = 2 [json_name = "isElectric"];</code>
     * @param value The isElectric to set.
     * @return This builder for chaining.
     */
    public Builder setIsElectric(boolean value) {

      isElectric_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_electric = 2 [json_name = "isElectric"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsElectric() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isElectric_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bike)
  }

  // @@protoc_insertion_point(class_scope:bike)
  private static final bike DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bike();
  }

  public static bike getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<bike>
      PARSER = new com.google.protobuf.AbstractParser<bike>() {
    @java.lang.Override
    public bike parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<bike> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<bike> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bike getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

