// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_identification.proto

// Protobuf Java Version: 4.26.1
public interface bike_identificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bike_identification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * uuid
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * uuid
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string model = 2 [json_name = "model"];</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>string model = 2 [json_name = "model"];</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();
}
