// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_reserved.proto
// Protobuf Java Version: 4.26.1

public final class BikeReservedProto {
  private BikeReservedProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      BikeReservedProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bike_reserved_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bike_reserved_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bike_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bike_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031bikes/bike_reserved.proto\032\037google/prot" +
      "obuf/timestamp.proto\032\037bikes/bike_identif" +
      "ication.proto\032%stations/station_identifi" +
      "cation.proto\032\037users/user_identification." +
      "proto\"\302\001\n\rbike_reserved\0229\n\ntime_stamp\030\001 " +
      "\001(\0132\032.google.protobuf.TimestampR\ttimeSta" +
      "mp\022\031\n\004bike\030\002 \001(\0132\005.bikeR\004bike\0221\n\007station" +
      "\030\003 \001(\0132\027.station_identificationR\007station" +
      "\022(\n\004user\030\004 \001(\0132\024.user_identificationR\004us" +
      "er\"Q\n\004bike\022(\n\004bike\030\001 \001(\0132\024.bike_identifi" +
      "cationR\004bike\022\037\n\013is_electric\030\002 \001(\010R\nisEle" +
      "ctricB3B\021BikeReservedProtoP\001Z\034stage2024/" +
      "pkg/protogen/bikesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          BikeIdentificationProto.getDescriptor(),
          StationIdentificationProto.getDescriptor(),
          UserIdentificationProto.getDescriptor(),
        });
    internal_static_bike_reserved_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bike_reserved_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bike_reserved_descriptor,
        new java.lang.String[] { "TimeStamp", "Bike", "Station", "User", });
    internal_static_bike_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bike_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bike_descriptor,
        new java.lang.String[] { "Bike", "IsElectric", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    BikeIdentificationProto.getDescriptor();
    StationIdentificationProto.getDescriptor();
    UserIdentificationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
