// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_immobilized.proto

// Protobuf Java Version: 4.26.1
/**
 * Protobuf type {@code bike_immobilized}
 */
public final class bike_immobilized extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bike_immobilized)
    bike_immobilizedOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      bike_immobilized.class.getName());
  }
  // Use bike_immobilized.newBuilder() to construct.
  private bike_immobilized(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private bike_immobilized() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BikeImmobilizedProto.internal_static_bike_immobilized_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BikeImmobilizedProto.internal_static_bike_immobilized_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bike_immobilized.class, bike_immobilized.Builder.class);
  }

  private int bitField0_;
  public static final int TIME_STAMP_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp timeStamp_;
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return Whether the timeStamp field is set.
   */
  @java.lang.Override
  public boolean hasTimeStamp() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return The timeStamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimeStamp() {
    return timeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder() {
    return timeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
  }

  public static final int BIKE_FIELD_NUMBER = 2;
  private location_bike bike_;
  /**
   * <code>.location_bike bike = 2 [json_name = "bike"];</code>
   * @return Whether the bike field is set.
   */
  @java.lang.Override
  public boolean hasBike() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.location_bike bike = 2 [json_name = "bike"];</code>
   * @return The bike.
   */
  @java.lang.Override
  public location_bike getBike() {
    return bike_ == null ? location_bike.getDefaultInstance() : bike_;
  }
  /**
   * <code>.location_bike bike = 2 [json_name = "bike"];</code>
   */
  @java.lang.Override
  public location_bikeOrBuilder getBikeOrBuilder() {
    return bike_ == null ? location_bike.getDefaultInstance() : bike_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getTimeStamp());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getBike());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTimeStamp());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBike());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bike_immobilized)) {
      return super.equals(obj);
    }
    bike_immobilized other = (bike_immobilized) obj;

    if (hasTimeStamp() != other.hasTimeStamp()) return false;
    if (hasTimeStamp()) {
      if (!getTimeStamp()
          .equals(other.getTimeStamp())) return false;
    }
    if (hasBike() != other.hasBike()) return false;
    if (hasBike()) {
      if (!getBike()
          .equals(other.getBike())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTimeStamp()) {
      hash = (37 * hash) + TIME_STAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
    }
    if (hasBike()) {
      hash = (37 * hash) + BIKE_FIELD_NUMBER;
      hash = (53 * hash) + getBike().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bike_immobilized parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bike_immobilized parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bike_immobilized parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bike_immobilized parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bike_immobilized parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bike_immobilized parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bike_immobilized parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bike_immobilized parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static bike_immobilized parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static bike_immobilized parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bike_immobilized parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bike_immobilized parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bike_immobilized prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bike_immobilized}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bike_immobilized)
      bike_immobilizedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BikeImmobilizedProto.internal_static_bike_immobilized_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BikeImmobilizedProto.internal_static_bike_immobilized_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bike_immobilized.class, bike_immobilized.Builder.class);
    }

    // Construct using bike_immobilized.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getTimeStampFieldBuilder();
        getBikeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      bike_ = null;
      if (bikeBuilder_ != null) {
        bikeBuilder_.dispose();
        bikeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BikeImmobilizedProto.internal_static_bike_immobilized_descriptor;
    }

    @java.lang.Override
    public bike_immobilized getDefaultInstanceForType() {
      return bike_immobilized.getDefaultInstance();
    }

    @java.lang.Override
    public bike_immobilized build() {
      bike_immobilized result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bike_immobilized buildPartial() {
      bike_immobilized result = new bike_immobilized(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(bike_immobilized result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.timeStamp_ = timeStampBuilder_ == null
            ? timeStamp_
            : timeStampBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.bike_ = bikeBuilder_ == null
            ? bike_
            : bikeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bike_immobilized) {
        return mergeFrom((bike_immobilized)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bike_immobilized other) {
      if (other == bike_immobilized.getDefaultInstance()) return this;
      if (other.hasTimeStamp()) {
        mergeTimeStamp(other.getTimeStamp());
      }
      if (other.hasBike()) {
        mergeBike(other.getBike());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTimeStampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getBikeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Timestamp timeStamp_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeStampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     * @return Whether the timeStamp field is set.
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     * @return The timeStamp.
     */
    public com.google.protobuf.Timestamp getTimeStamp() {
      if (timeStampBuilder_ == null) {
        return timeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
      } else {
        return timeStampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public Builder setTimeStamp(com.google.protobuf.Timestamp value) {
      if (timeStampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeStamp_ = value;
      } else {
        timeStampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public Builder setTimeStamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timeStampBuilder_ == null) {
        timeStamp_ = builderForValue.build();
      } else {
        timeStampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public Builder mergeTimeStamp(com.google.protobuf.Timestamp value) {
      if (timeStampBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          timeStamp_ != null &&
          timeStamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimeStampBuilder().mergeFrom(value);
        } else {
          timeStamp_ = value;
        }
      } else {
        timeStampBuilder_.mergeFrom(value);
      }
      if (timeStamp_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public Builder clearTimeStamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timeStamp_ = null;
      if (timeStampBuilder_ != null) {
        timeStampBuilder_.dispose();
        timeStampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimeStampBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTimeStampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder() {
      if (timeStampBuilder_ != null) {
        return timeStampBuilder_.getMessageOrBuilder();
      } else {
        return timeStamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timeStamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimeStampFieldBuilder() {
      if (timeStampBuilder_ == null) {
        timeStampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimeStamp(),
                getParentForChildren(),
                isClean());
        timeStamp_ = null;
      }
      return timeStampBuilder_;
    }

    private location_bike bike_;
    private com.google.protobuf.SingleFieldBuilder<
        location_bike, location_bike.Builder, location_bikeOrBuilder> bikeBuilder_;
    /**
     * <code>.location_bike bike = 2 [json_name = "bike"];</code>
     * @return Whether the bike field is set.
     */
    public boolean hasBike() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.location_bike bike = 2 [json_name = "bike"];</code>
     * @return The bike.
     */
    public location_bike getBike() {
      if (bikeBuilder_ == null) {
        return bike_ == null ? location_bike.getDefaultInstance() : bike_;
      } else {
        return bikeBuilder_.getMessage();
      }
    }
    /**
     * <code>.location_bike bike = 2 [json_name = "bike"];</code>
     */
    public Builder setBike(location_bike value) {
      if (bikeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bike_ = value;
      } else {
        bikeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.location_bike bike = 2 [json_name = "bike"];</code>
     */
    public Builder setBike(
        location_bike.Builder builderForValue) {
      if (bikeBuilder_ == null) {
        bike_ = builderForValue.build();
      } else {
        bikeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.location_bike bike = 2 [json_name = "bike"];</code>
     */
    public Builder mergeBike(location_bike value) {
      if (bikeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          bike_ != null &&
          bike_ != location_bike.getDefaultInstance()) {
          getBikeBuilder().mergeFrom(value);
        } else {
          bike_ = value;
        }
      } else {
        bikeBuilder_.mergeFrom(value);
      }
      if (bike_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.location_bike bike = 2 [json_name = "bike"];</code>
     */
    public Builder clearBike() {
      bitField0_ = (bitField0_ & ~0x00000002);
      bike_ = null;
      if (bikeBuilder_ != null) {
        bikeBuilder_.dispose();
        bikeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.location_bike bike = 2 [json_name = "bike"];</code>
     */
    public location_bike.Builder getBikeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getBikeFieldBuilder().getBuilder();
    }
    /**
     * <code>.location_bike bike = 2 [json_name = "bike"];</code>
     */
    public location_bikeOrBuilder getBikeOrBuilder() {
      if (bikeBuilder_ != null) {
        return bikeBuilder_.getMessageOrBuilder();
      } else {
        return bike_ == null ?
            location_bike.getDefaultInstance() : bike_;
      }
    }
    /**
     * <code>.location_bike bike = 2 [json_name = "bike"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        location_bike, location_bike.Builder, location_bikeOrBuilder> 
        getBikeFieldBuilder() {
      if (bikeBuilder_ == null) {
        bikeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            location_bike, location_bike.Builder, location_bikeOrBuilder>(
                getBike(),
                getParentForChildren(),
                isClean());
        bike_ = null;
      }
      return bikeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:bike_immobilized)
  }

  // @@protoc_insertion_point(class_scope:bike_immobilized)
  private static final bike_immobilized DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bike_immobilized();
  }

  public static bike_immobilized getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<bike_immobilized>
      PARSER = new com.google.protobuf.AbstractParser<bike_immobilized>() {
    @java.lang.Override
    public bike_immobilized parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<bike_immobilized> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<bike_immobilized> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bike_immobilized getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

