// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_defect_reported.proto

// Protobuf Java Version: 4.26.1
public interface defect_bikeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:defect_bike)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
   * @return Whether the bike field is set.
   */
  boolean hasBike();
  /**
   * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
   * @return The bike.
   */
  bike_identification getBike();
  /**
   * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
   */
  bike_identificationOrBuilder getBikeOrBuilder();

  /**
   * <code>.location location = 2 [json_name = "location"];</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.location location = 2 [json_name = "location"];</code>
   * @return The location.
   */
  location getLocation();
  /**
   * <code>.location location = 2 [json_name = "location"];</code>
   */
  locationOrBuilder getLocationOrBuilder();

  /**
   * <code>bool is_electric = 3 [json_name = "isElectric"];</code>
   * @return The isElectric.
   */
  boolean getIsElectric();

  /**
   * <code>bool is_immobilized = 4 [json_name = "isImmobilized"];</code>
   * @return The isImmobilized.
   */
  boolean getIsImmobilized();
}
