// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stations/station_deprecated.proto

// Protobuf Java Version: 4.26.1
public interface deprecated_stationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deprecated_station)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.station_identification station = 1 [json_name = "station"];</code>
   * @return Whether the station field is set.
   */
  boolean hasStation();
  /**
   * <code>.station_identification station = 1 [json_name = "station"];</code>
   * @return The station.
   */
  station_identification getStation();
  /**
   * <code>.station_identification station = 1 [json_name = "station"];</code>
   */
  station_identificationOrBuilder getStationOrBuilder();

  /**
   * <code>bool is_active = 2 [json_name = "isActive"];</code>
   * @return The isActive.
   */
  boolean getIsActive();
}
