// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bikes/bike_immobilized.proto

// Protobuf Java Version: 4.26.1
public interface location_bikeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:location_bike)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
   * @return Whether the bike field is set.
   */
  boolean hasBike();
  /**
   * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
   * @return The bike.
   */
  bike_identification getBike();
  /**
   * <code>.bike_identification bike = 1 [json_name = "bike"];</code>
   */
  bike_identificationOrBuilder getBikeOrBuilder();

  /**
   * <code>.location location = 2 [json_name = "location"];</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.location location = 2 [json_name = "location"];</code>
   * @return The location.
   */
  location getLocation();
  /**
   * <code>.location location = 2 [json_name = "location"];</code>
   */
  locationOrBuilder getLocationOrBuilder();
}
