// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/location.proto

// Protobuf Java Version: 4.26.1
public interface locationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:location)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double latitude = 1 [json_name = "latitude"];</code>
   * @return The latitude.
   */
  double getLatitude();

  /**
   * <code>double longitude = 2 [json_name = "longitude"];</code>
   * @return The longitude.
   */
  double getLongitude();
}
