// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stations/station_full.proto

// Protobuf Java Version: 4.26.1
public interface station_fullOrBuilder extends
    // @@protoc_insertion_point(interface_extends:station_full)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return Whether the timeStamp field is set.
   */
  boolean hasTimeStamp();
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return The timeStamp.
   */
  com.google.protobuf.Timestamp getTimeStamp();
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder();

  /**
   * <code>.station_identification station = 2 [json_name = "station"];</code>
   * @return Whether the station field is set.
   */
  boolean hasStation();
  /**
   * <code>.station_identification station = 2 [json_name = "station"];</code>
   * @return The station.
   */
  station_identification getStation();
  /**
   * <code>.station_identification station = 2 [json_name = "station"];</code>
   */
  station_identificationOrBuilder getStationOrBuilder();

  /**
   * <code>int32 max_capacity = 3 [json_name = "maxCapacity"];</code>
   * @return The maxCapacity.
   */
  int getMaxCapacity();
}
