// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stations/station_occupation_decreased.proto

// Protobuf Java Version: 4.26.1
public interface station_occupation_decreasedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:station_occupation_decreased)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return Whether the timeStamp field is set.
   */
  boolean hasTimeStamp();
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return The timeStamp.
   */
  com.google.protobuf.Timestamp getTimeStamp();
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder();

  /**
   * <code>.station_identification station = 2 [json_name = "station"];</code>
   * @return Whether the station field is set.
   */
  boolean hasStation();
  /**
   * <code>.station_identification station = 2 [json_name = "station"];</code>
   * @return The station.
   */
  station_identification getStation();
  /**
   * <code>.station_identification station = 2 [json_name = "station"];</code>
   */
  station_identificationOrBuilder getStationOrBuilder();

  /**
   * <code>int32 amount_decreased = 3 [json_name = "amountDecreased"];</code>
   * @return The amountDecreased.
   */
  int getAmountDecreased();

  /**
   * <code>int32 current_available_capacity = 4 [json_name = "currentAvailableCapacity"];</code>
   * @return The currentAvailableCapacity.
   */
  int getCurrentAvailableCapacity();

  /**
   * <code>int32 max_capacity = 5 [json_name = "maxCapacity"];</code>
   * @return The maxCapacity.
   */
  int getMaxCapacity();
}
