// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stations/station_deprecated.proto
// Protobuf Java Version: 4.26.1

public final class StationDeprecatedProto {
  private StationDeprecatedProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      StationDeprecatedProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_station_deprecated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_station_deprecated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deprecated_station_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_deprecated_station_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!stations/station_deprecated.proto\032\037goo" +
      "gle/protobuf/timestamp.proto\032%stations/s" +
      "tation_identification.proto\"~\n\022station_d" +
      "eprecated\0229\n\ntime_stamp\030\001 \001(\0132\032.google.p" +
      "rotobuf.TimestampR\ttimeStamp\022-\n\007station\030" +
      "\002 \001(\0132\023.deprecated_stationR\007station\"d\n\022d" +
      "eprecated_station\0221\n\007station\030\001 \001(\0132\027.sta" +
      "tion_identificationR\007station\022\033\n\tis_activ" +
      "e\030\002 \001(\010R\010isActiveB;B\026StationDeprecatedPr" +
      "otoP\001Z\037stage2024/pkg/protogen/stationsb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          StationIdentificationProto.getDescriptor(),
        });
    internal_static_station_deprecated_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_station_deprecated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_station_deprecated_descriptor,
        new java.lang.String[] { "TimeStamp", "Station", });
    internal_static_deprecated_station_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_deprecated_station_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_deprecated_station_descriptor,
        new java.lang.String[] { "Station", "IsActive", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    StationIdentificationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
