// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stations/station_identification.proto

// Protobuf Java Version: 4.26.1
public interface station_identificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:station_identification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * uuid
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * uuid
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.location location = 2 [json_name = "location"];</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.location location = 2 [json_name = "location"];</code>
   * @return The location.
   */
  location getLocation();
  /**
   * <code>.location location = 2 [json_name = "location"];</code>
   */
  locationOrBuilder getLocationOrBuilder();

  /**
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
