// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stations/station_created.proto
// Protobuf Java Version: 4.26.1

public final class StationCreatedProto {
  private StationCreatedProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      StationCreatedProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_station_created_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_station_created_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_created_station_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_created_station_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036stations/station_created.proto\032\037google" +
      "/protobuf/timestamp.proto\032%stations/stat" +
      "ion_identification.proto\"x\n\017station_crea" +
      "ted\0229\n\ntime_stamp\030\001 \001(\0132\032.google.protobu" +
      "f.TimestampR\ttimeStamp\022*\n\007station\030\002 \001(\0132" +
      "\020.created_stationR\007station\"\204\001\n\017created_s" +
      "tation\0221\n\007station\030\001 \001(\0132\027.station_identi" +
      "ficationR\007station\022\033\n\tis_active\030\002 \001(\010R\010is" +
      "Active\022!\n\014max_capacity\030\003 \001(\005R\013maxCapacit" +
      "yB8B\023StationCreatedProtoP\001Z\037stage2024/pk" +
      "g/protogen/stationsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          StationIdentificationProto.getDescriptor(),
        });
    internal_static_station_created_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_station_created_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_station_created_descriptor,
        new java.lang.String[] { "TimeStamp", "Station", });
    internal_static_created_station_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_created_station_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_created_station_descriptor,
        new java.lang.String[] { "Station", "IsActive", "MaxCapacity", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    StationIdentificationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
