// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stations/station_identification.proto
// Protobuf Java Version: 4.26.1

public final class StationIdentificationProto {
  private StationIdentificationProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      StationIdentificationProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_station_identification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_station_identification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%stations/station_identification.proto\032" +
      "\025common/location.proto\"c\n\026station_identi" +
      "fication\022\016\n\002id\030\001 \001(\tR\002id\022%\n\010location\030\002 \001" +
      "(\0132\t.locationR\010location\022\022\n\004name\030\003 \001(\tR\004n" +
      "ameB?B\032StationIdentificationProtoP\001Z\037sta" +
      "ge2024/pkg/protogen/stationsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          LocationProto.getDescriptor(),
        });
    internal_static_station_identification_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_station_identification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_station_identification_descriptor,
        new java.lang.String[] { "Id", "Location", "Name", });
    descriptor.resolveAllFeaturesImmutable();
    LocationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
