// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stations/station_deprecated.proto

// Protobuf Java Version: 4.26.1
public interface station_deprecatedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:station_deprecated)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return Whether the timeStamp field is set.
   */
  boolean hasTimeStamp();
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return The timeStamp.
   */
  com.google.protobuf.Timestamp getTimeStamp();
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder();

  /**
   * <code>.deprecated_station station = 2 [json_name = "station"];</code>
   * @return Whether the station field is set.
   */
  boolean hasStation();
  /**
   * <code>.deprecated_station station = 2 [json_name = "station"];</code>
   * @return The station.
   */
  deprecated_station getStation();
  /**
   * <code>.deprecated_station station = 2 [json_name = "station"];</code>
   */
  deprecated_stationOrBuilder getStationOrBuilder();
}
