// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users/user_identification.proto

// Protobuf Java Version: 4.26.1
public interface user_identificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user_identification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * uuid
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * uuid
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string user_name = 2 [json_name = "userName"];</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string user_name = 2 [json_name = "userName"];</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string email_address = 3 [json_name = "emailAddress"];</code>
   * @return The emailAddress.
   */
  java.lang.String getEmailAddress();
  /**
   * <code>string email_address = 3 [json_name = "emailAddress"];</code>
   * @return The bytes for emailAddress.
   */
  com.google.protobuf.ByteString
      getEmailAddressBytes();
}
