// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users/user_registered.proto
// Protobuf Java Version: 4.26.1

public final class UserRegisteredProto {
  private UserRegisteredProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      UserRegisteredProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_registered_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_user_registered_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033users/user_registered.proto\032\037google/pr" +
      "otobuf/timestamp.proto\032\037users/user_ident" +
      "ification.proto\"v\n\017user_registered\0229\n\nti" +
      "me_stamp\030\001 \001(\0132\032.google.protobuf.Timesta" +
      "mpR\ttimeStamp\022(\n\004user\030\002 \001(\0132\024.user_ident" +
      "ificationR\004userB5B\023UserRegisteredProtoP\001" +
      "Z\034stage2024/pkg/protogen/usersb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          UserIdentificationProto.getDescriptor(),
        });
    internal_static_user_registered_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_registered_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_user_registered_descriptor,
        new java.lang.String[] { "TimeStamp", "User", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    UserIdentificationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
