// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users/user_registered.proto

// Protobuf Java Version: 4.26.1
public interface user_registeredOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user_registered)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return Whether the timeStamp field is set.
   */
  boolean hasTimeStamp();
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   * @return The timeStamp.
   */
  com.google.protobuf.Timestamp getTimeStamp();
  /**
   * <code>.google.protobuf.Timestamp time_stamp = 1 [json_name = "timeStamp"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeStampOrBuilder();

  /**
   * <code>.user_identification user = 2 [json_name = "user"];</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.user_identification user = 2 [json_name = "user"];</code>
   * @return The user.
   */
  user_identification getUser();
  /**
   * <code>.user_identification user = 2 [json_name = "user"];</code>
   */
  user_identificationOrBuilder getUserOrBuilder();
}
